[pe]
name = "PE"
desc = "Polyethylene"

[pp]
name = "PP"
desc = "Polypropylene"

[ps]
name = "PS"
desc = "Polystyrene"

[pvc]
name = "PVC"
desc = "Polyvinyl Chloride"

[pta]
name = "PTA"
desc = "Pure Terephthalic Acid"

[pnt]
name = "PNT"
desc = "Positioning, Navigation and Timing"
