[pvc]
name = "PVC"
desc = "Polyvinyl Chloride"

[pta]
name = "PTA"
desc = "Pure Terephthalic Acid"

[pnt]
name = "PNT"
desc = "Positioning, Navigation and Timing"

[pe]
name = "PE"
desc = "Polyethylene"
